/**
 * Type names that every TypeScript program already has.
 *
 * Generated from the `lib.*.d.ts` files TypeScript ships, plus the Node and
 * Bun ambients that live outside them. Referencing one of these from a
 * declaration is never dangling, so `dangling-refs` treats the whole set as
 * resolved.
 *
 * Whether a given consumer actually loads `lib.dom` depends on their tsconfig,
 * so a Node-only package referencing `HTMLElement` is arguably broken and is
 * not reported here. That is deliberate: this check exists to catch names that
 * resolve nowhere, and a false positive that fails a build is far more
 * expensive than a miss.
 *
 * Regenerate with `bun scripts/generate-global-types.ts`.
 */
export const GLOBAL_TYPE_NAMES: ReadonlySet<string> = new Set([
  'ANGLE_instanced_arrays', 'ARIAMixin', 'AacBitstreamFormat',
  'AacEncoderConfig', 'AbortController', 'AbortSignal', 'AbortSignalEventMap',
  'AbstractRange', 'AbstractWorker', 'AbstractWorkerEventMap',
  'ActiveXObject', 'AddEventListenerOptions', 'AddressErrors', 'AddressType',
  'AddressValue', 'AesCbcParams', 'AesCtrParams', 'AesDerivedKeyParams',
  'AesGcmParams', 'AesKeyAlgorithm', 'AesKeyGenParams', 'AggregateError',
  'AggregateErrorConstructor', 'Algorithm', 'AlgorithmIdentifier',
  'AlignSetting', 'AllAcceptedCredentialsOptions', 'AllowSharedBufferSource',
  'AlphaOption', 'AnalyserNode', 'AnalyserOptions', 'Animatable', 'Animation',
  'AnimationEffect', 'AnimationEvent', 'AnimationEventInit',
  'AnimationEventMap', 'AnimationFrameProvider', 'AnimationPlayState',
  'AnimationPlaybackEvent', 'AnimationPlaybackEventInit',
  'AnimationReplaceState', 'AnimationTimeline', 'AppendMode', 'Array',
  'ArrayBuffer', 'ArrayBufferConstructor', 'ArrayBufferLike',
  'ArrayBufferTypes', 'ArrayBufferView', 'ArrayConstructor', 'ArrayIterator',
  'ArrayLike', 'AssignedNodesOptions', 'AsyncDisposable',
  'AsyncDisposableStack', 'AsyncDisposableStackConstructor', 'AsyncGenerator',
  'AsyncGeneratorFunction', 'AsyncGeneratorFunctionConstructor',
  'AsyncIterable', 'AsyncIterableIterator', 'AsyncIterator',
  'AsyncIteratorObject', 'Atomics', 'AttestationConveyancePreference', 'Attr',
  'Audio', 'AudioBuffer', 'AudioBufferOptions', 'AudioBufferSourceNode',
  'AudioBufferSourceOptions', 'AudioConfiguration', 'AudioContext',
  'AudioContextLatencyCategory', 'AudioContextOptions', 'AudioContextState',
  'AudioData', 'AudioDataCopyToOptions', 'AudioDataInit',
  'AudioDataOutputCallback', 'AudioDecoder', 'AudioDecoderConfig',
  'AudioDecoderEventMap', 'AudioDecoderInit', 'AudioDecoderSupport',
  'AudioDestinationNode', 'AudioEncoder', 'AudioEncoderConfig',
  'AudioEncoderEventMap', 'AudioEncoderInit', 'AudioEncoderSupport',
  'AudioListener', 'AudioNode', 'AudioNodeOptions', 'AudioParam',
  'AudioParamMap', 'AudioProcessingEvent', 'AudioProcessingEventInit',
  'AudioSampleFormat', 'AudioScheduledSourceNode',
  'AudioScheduledSourceNodeEventMap', 'AudioTimestamp', 'AudioWorklet',
  'AudioWorkletNode', 'AudioWorkletNodeEventMap', 'AudioWorkletNodeOptions',
  'AuthenticationExtensionsClientInputs',
  'AuthenticationExtensionsClientInputsJSON',
  'AuthenticationExtensionsClientOutputs',
  'AuthenticationExtensionsClientOutputsJSON',
  'AuthenticationExtensionsLargeBlobInputs',
  'AuthenticationExtensionsLargeBlobInputsJSON',
  'AuthenticationExtensionsLargeBlobOutputs',
  'AuthenticationExtensionsLargeBlobOutputsJSON',
  'AuthenticationExtensionsPRFInputs',
  'AuthenticationExtensionsPRFInputsJSON',
  'AuthenticationExtensionsPRFOutputs',
  'AuthenticationExtensionsPRFOutputsJSON',
  'AuthenticationExtensionsPRFValues',
  'AuthenticationExtensionsPRFValuesJSON', 'AuthenticationResponseJSON',
  'AuthenticatorAssertionResponse', 'AuthenticatorAssertionResponseJSON',
  'AuthenticatorAttachment', 'AuthenticatorAttestationResponse',
  'AuthenticatorAttestationResponseJSON', 'AuthenticatorResponse',
  'AuthenticatorSelectionCriteria', 'AuthenticatorTransport', 'AutoFill',
  'AutoFillAddressKind', 'AutoFillBase', 'AutoFillContactField',
  'AutoFillContactKind', 'AutoFillCredentialField', 'AutoFillField',
  'AutoFillNormalField', 'AutoFillSection', 'AutoKeyword', 'AutomationRate',
  'AvcBitstreamFormat', 'AvcEncoderConfig', 'Awaited', 'BarProp',
  'Base64URLString', 'BaseAudioContext', 'BaseAudioContextEventMap',
  'BeforeUnloadEvent', 'BigInt', 'BigInt64Array', 'BigInt64ArrayConstructor',
  'BigIntConstructor', 'BigIntToLocaleStringOptions', 'BigInteger',
  'BigUint64Array', 'BigUint64ArrayConstructor', 'BinaryType',
  'BiquadFilterNode', 'BiquadFilterOptions', 'BiquadFilterType',
  'BitrateMode', 'Blob', 'BlobCallback', 'BlobEvent', 'BlobEventInit',
  'BlobPart', 'BlobPropertyBag', 'Body', 'BodyInit', 'Boolean',
  'BooleanConstructor', 'BroadcastChannel', 'BroadcastChannelEventMap',
  'Buffer', 'BufferEncoding', 'BufferSource', 'BuiltinIteratorReturn', 'Bun',
  'BunFile', 'ByteLengthQueuingStrategy', 'CDATASection',
  'COSEAlgorithmIdentifier', 'CSS', 'CSSAnimation', 'CSSConditionRule',
  'CSSContainerRule', 'CSSCounterStyleRule', 'CSSFontFaceRule',
  'CSSFontFeatureValuesRule', 'CSSFontPaletteValuesRule', 'CSSGroupingRule',
  'CSSImageValue', 'CSSImportRule', 'CSSKeyframeRule', 'CSSKeyframesRule',
  'CSSKeywordValue', 'CSSKeywordish', 'CSSLayerBlockRule',
  'CSSLayerStatementRule', 'CSSMathClamp', 'CSSMathInvert', 'CSSMathMax',
  'CSSMathMin', 'CSSMathNegate', 'CSSMathOperator', 'CSSMathProduct',
  'CSSMathSum', 'CSSMathValue', 'CSSMatrixComponent',
  'CSSMatrixComponentOptions', 'CSSMediaRule', 'CSSNamespaceRule',
  'CSSNestedDeclarations', 'CSSNumberish', 'CSSNumericArray',
  'CSSNumericBaseType', 'CSSNumericType', 'CSSNumericValue',
  'CSSPageDescriptors', 'CSSPageRule', 'CSSPerspective',
  'CSSPerspectiveValue', 'CSSPositionTryDescriptors', 'CSSPositionTryRule',
  'CSSPropertyRule', 'CSSRotate', 'CSSRule', 'CSSRuleList', 'CSSScale',
  'CSSScopeRule', 'CSSSkew', 'CSSSkewX', 'CSSSkewY', 'CSSStartingStyleRule',
  'CSSStyleDeclaration', 'CSSStyleDeclarationBase', 'CSSStyleProperties',
  'CSSStyleRule', 'CSSStyleSheet', 'CSSStyleSheetInit', 'CSSStyleValue',
  'CSSSupportsRule', 'CSSTransformComponent', 'CSSTransformValue',
  'CSSTransition', 'CSSTranslate', 'CSSUnitValue', 'CSSUnparsedSegment',
  'CSSUnparsedValue', 'CSSVariableReferenceValue', 'CSSViewTransitionRule',
  'Cache', 'CacheQueryOptions', 'CacheStorage', 'CalendarLike',
  'CallableFunction', 'CanPlayTypeResult', 'CanvasCaptureMediaStreamTrack',
  'CanvasCompositing', 'CanvasDirection', 'CanvasDrawImage', 'CanvasDrawPath',
  'CanvasFillRule', 'CanvasFillStrokeStyles', 'CanvasFilters',
  'CanvasFontKerning', 'CanvasFontStretch', 'CanvasFontVariantCaps',
  'CanvasGradient', 'CanvasImageData', 'CanvasImageSmoothing',
  'CanvasImageSource', 'CanvasLineCap', 'CanvasLineJoin', 'CanvasPath',
  'CanvasPathDrawingStyles', 'CanvasPattern', 'CanvasRect',
  'CanvasRenderingContext2D', 'CanvasRenderingContext2DSettings',
  'CanvasSettings', 'CanvasShadowStyles', 'CanvasState', 'CanvasText',
  'CanvasTextAlign', 'CanvasTextBaseline', 'CanvasTextDrawingStyles',
  'CanvasTextRendering', 'CanvasTransform', 'CanvasUserInterface',
  'Capitalize', 'CaretPosition', 'CaretPositionFromPointOptions',
  'ChannelCountMode', 'ChannelInterpretation', 'ChannelMergerNode',
  'ChannelMergerOptions', 'ChannelSplitterNode', 'ChannelSplitterOptions',
  'CharacterData', 'CheckVisibilityOptions', 'ChildNode',
  'ClassAccessorDecoratorContext', 'ClassAccessorDecoratorResult',
  'ClassAccessorDecoratorTarget', 'ClassDecorator', 'ClassDecoratorContext',
  'ClassFieldDecoratorContext', 'ClassGetterDecoratorContext',
  'ClassMemberDecoratorContext', 'ClassMethodDecoratorContext',
  'ClassSetterDecoratorContext', 'Client', 'ClientQueryOptions', 'ClientRect',
  'ClientTypes', 'Clients', 'Clipboard', 'ClipboardEvent',
  'ClipboardEventInit', 'ClipboardItem', 'ClipboardItemData',
  'ClipboardItemOptions', 'ClipboardItems', 'CloseEvent', 'CloseEventInit',
  'CodecState', 'Collator', 'CollatorConstructor', 'CollatorOptions',
  'ColorGamut', 'ColorSpaceConversion', 'CommandEvent', 'CommandEventInit',
  'Comment', 'CompileError', 'CompositeOperation', 'CompositeOperationOrAuto',
  'CompositionEvent', 'CompositionEventInit', 'CompressionFormat',
  'CompressionStream', 'ComputedEffectTiming', 'ComputedKeyframe',
  'ConcatArray', 'Console', 'ConstantSourceNode', 'ConstantSourceOptions',
  'ConstrainBoolean', 'ConstrainBooleanOrDOMString',
  'ConstrainBooleanOrDOMStringParameters', 'ConstrainBooleanParameters',
  'ConstrainDOMString', 'ConstrainDOMStringParameters', 'ConstrainDouble',
  'ConstrainDoubleRange', 'ConstrainULong', 'ConstrainULongRange',
  'ConstructorParameters', 'ContentVisibilityAutoStateChangeEvent',
  'ContentVisibilityAutoStateChangeEventInit', 'ConvolverNode',
  'ConvolverOptions', 'CookieChangeEvent', 'CookieChangeEventInit',
  'CookieInit', 'CookieList', 'CookieListItem', 'CookieSameSite',
  'CookieStore', 'CookieStoreDeleteOptions', 'CookieStoreEventMap',
  'CookieStoreGetOptions', 'CookieStoreManager', 'CountQueuingStrategy',
  'Credential', 'CredentialCreationOptions', 'CredentialMediationRequirement',
  'CredentialPropertiesOutput', 'CredentialRequestOptions',
  'CredentialsContainer', 'Crypto', 'CryptoKey', 'CryptoKeyPair',
  'CurrentUserDetailsOptions', 'CustomElementConstructor',
  'CustomElementRegistry', 'CustomEvent', 'CustomEventInit', 'CustomStateSet',
  'DOMException', 'DOMHighResTimeStamp', 'DOMImplementation', 'DOMMatrix',
  'DOMMatrix2DInit', 'DOMMatrixInit', 'DOMMatrixReadOnly', 'DOMParser',
  'DOMParserSupportedType', 'DOMPoint', 'DOMPointInit', 'DOMPointReadOnly',
  'DOMQuad', 'DOMQuadInit', 'DOMRect', 'DOMRectInit', 'DOMRectList',
  'DOMRectReadOnly', 'DOMStringList', 'DOMStringMap', 'DOMTokenList',
  'DataTransfer', 'DataTransferItem', 'DataTransferItemList', 'DataView',
  'DataViewConstructor', 'Date', 'DateConstructor', 'DateLikeObject',
  'DateTimeFormat', 'DateTimeFormatConstructor', 'DateTimeFormatOptions',
  'DateTimeFormatPart', 'DateTimeFormatPartTypes',
  'DateTimeFormatPartTypesRegistry', 'DateTimeLikeObject',
  'DateTimeRangeFormatPart', 'DateUnit', 'DecodeErrorCallback',
  'DecodeSuccessCallback', 'DecompressionStream', 'DecoratorContext',
  'DecoratorMetadata', 'DecoratorMetadataObject',
  'DedicatedWorkerGlobalScope', 'DedicatedWorkerGlobalScopeEventMap',
  'DelayNode', 'DelayOptions', 'DeviceMotionEvent',
  'DeviceMotionEventAcceleration', 'DeviceMotionEventAccelerationInit',
  'DeviceMotionEventInit', 'DeviceMotionEventRotationRate',
  'DeviceMotionEventRotationRateInit', 'DeviceOrientationEvent',
  'DeviceOrientationEventInit', 'DigitalCredential', 'DirectionSetting',
  'Dirent', 'DisambiguationOptions', 'DisplayCaptureSurfaceType',
  'DisplayMediaStreamOptions', 'DisplayNames', 'DisplayNamesFallback',
  'DisplayNamesLanguageDisplay', 'DisplayNamesOptions', 'DisplayNamesType',
  'Disposable', 'DisposableStack', 'DisposableStackConstructor',
  'DistanceModelType', 'Document', 'DocumentEventMap', 'DocumentFragment',
  'DocumentOrShadowRoot', 'DocumentReadyState', 'DocumentTimeline',
  'DocumentTimelineOptions', 'DocumentType', 'DocumentVisibilityState',
  'DoubleRange', 'DragEvent', 'DragEventInit', 'Duration',
  'DurationConstructor', 'DurationFormat', 'DurationFormatDisplayOption',
  'DurationFormatLocaleMatcher', 'DurationFormatOptions',
  'DurationFormatPart', 'DurationFormatStyle', 'DurationFormatUnit',
  'DurationFormatUnitSingular', 'DurationLike', 'DurationLikeObject',
  'DurationRelativeToOptions', 'DurationRoundingOptions',
  'DurationToStringOptions', 'DurationTotalOptions', 'DynamicsCompressorNode',
  'DynamicsCompressorOptions', 'EXT_blend_minmax', 'EXT_color_buffer_float',
  'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth',
  'EXT_sRGB', 'EXT_shader_texture_lod', 'EXT_texture_compression_bptc',
  'EXT_texture_compression_rgtc', 'EXT_texture_filter_anisotropic',
  'EXT_texture_norm16', 'EcKeyAlgorithm', 'EcKeyGenParams',
  'EcKeyImportParams', 'EcdhKeyDeriveParams', 'EcdsaParams', 'EffectTiming',
  'Element', 'ElementCSSInlineStyle', 'ElementContentEditable',
  'ElementCreationOptions', 'ElementDefinitionOptions', 'ElementEventMap',
  'ElementInternals', 'ElementTagNameMap', 'EncodedAudioChunk',
  'EncodedAudioChunkInit', 'EncodedAudioChunkMetadata',
  'EncodedAudioChunkOutputCallback', 'EncodedAudioChunkType',
  'EncodedVideoChunk', 'EncodedVideoChunkInit', 'EncodedVideoChunkMetadata',
  'EncodedVideoChunkOutputCallback', 'EncodedVideoChunkType',
  'EndOfStreamError', 'EndingType', 'Enumerator', 'EnumeratorConstructor',
  'EpochTimeStamp', 'Error', 'ErrorCallback', 'ErrorConstructor',
  'ErrorEvent', 'ErrorEventInit', 'ErrorOptions', 'EvalError',
  'EvalErrorConstructor', 'Event', 'EventCounts', 'EventInit',
  'EventListener', 'EventListenerObject', 'EventListenerOptions',
  'EventListenerOrEventListenerObject', 'EventModifierInit', 'EventSource',
  'EventSourceEventMap', 'EventSourceInit', 'EventTarget', 'Exception',
  'ExceptionOptions', 'Exclude', 'ExportValue', 'Exports',
  'ExtendableCookieChangeEvent', 'ExtendableCookieChangeEventInit',
  'ExtendableEvent', 'ExtendableEventInit', 'ExtendableMessageEvent',
  'ExtendableMessageEventInit', 'External', 'Extract', 'FetchEvent',
  'FetchEventInit', 'File', 'FileCallback', 'FileList', 'FilePropertyBag',
  'FileReader', 'FileReaderEventMap', 'FileReaderSync', 'FileSink',
  'FileSystem', 'FileSystemCreateWritableOptions', 'FileSystemDirectoryEntry',
  'FileSystemDirectoryHandle', 'FileSystemDirectoryHandleAsyncIterator',
  'FileSystemDirectoryReader', 'FileSystemEntriesCallback', 'FileSystemEntry',
  'FileSystemEntryCallback', 'FileSystemFileEntry', 'FileSystemFileHandle',
  'FileSystemFlags', 'FileSystemGetDirectoryOptions',
  'FileSystemGetFileOptions', 'FileSystemHandle', 'FileSystemHandleKind',
  'FileSystemReadWriteOptions', 'FileSystemRemoveOptions',
  'FileSystemSyncAccessHandle', 'FileSystemWritableFileStream',
  'FileSystemWriteChunkType', 'FillLightMode', 'FillMode',
  'FinalizationRegistry', 'FinalizationRegistryConstructor', 'FlatArray',
  'Float16Array', 'Float16ArrayConstructor', 'Float32Array',
  'Float32ArrayConstructor', 'Float32List', 'Float64Array',
  'Float64ArrayConstructor', 'FocusEvent', 'FocusEventInit', 'FocusOptions',
  'FontDisplay', 'FontFace', 'FontFaceDescriptors', 'FontFaceLoadStatus',
  'FontFaceSet', 'FontFaceSetEventMap', 'FontFaceSetLoadEvent',
  'FontFaceSetLoadEventInit', 'FontFaceSetLoadStatus', 'FontFaceSource',
  'FormData', 'FormDataEntryValue', 'FormDataEvent', 'FormDataEventInit',
  'FormDataIterator', 'FormattableTemporalObject', 'FragmentDirective',
  'FrameRequestCallback', 'FrameType', 'FullscreenNavigationUI',
  'FullscreenOptions', 'Function', 'FunctionConstructor',
  'FunctionStringCallback', 'GLbitfield', 'GLboolean', 'GLclampf', 'GLenum',
  'GLfloat', 'GLint', 'GLint64', 'GLintptr', 'GLsizei', 'GLsizeiptr',
  'GLuint', 'GLuint64', 'GPU', 'GPUAdapter', 'GPUAdapterInfo',
  'GPUAddressMode', 'GPUAutoLayoutMode', 'GPUBindGroup',
  'GPUBindGroupDescriptor', 'GPUBindGroupEntry', 'GPUBindGroupLayout',
  'GPUBindGroupLayoutDescriptor', 'GPUBindGroupLayoutEntry',
  'GPUBindingCommandsMixin', 'GPUBindingResource', 'GPUBlendComponent',
  'GPUBlendFactor', 'GPUBlendOperation', 'GPUBlendState', 'GPUBuffer',
  'GPUBufferBinding', 'GPUBufferBindingLayout', 'GPUBufferBindingType',
  'GPUBufferDescriptor', 'GPUBufferDynamicOffset', 'GPUBufferMapState',
  'GPUBufferUsageFlags', 'GPUCanvasAlphaMode', 'GPUCanvasConfiguration',
  'GPUCanvasContext', 'GPUCanvasToneMapping', 'GPUCanvasToneMappingMode',
  'GPUColor', 'GPUColorDict', 'GPUColorTargetState', 'GPUColorWriteFlags',
  'GPUCommandBuffer', 'GPUCommandBufferDescriptor', 'GPUCommandEncoder',
  'GPUCommandEncoderDescriptor', 'GPUCompareFunction', 'GPUCompilationInfo',
  'GPUCompilationMessage', 'GPUCompilationMessageType',
  'GPUComputePassDescriptor', 'GPUComputePassEncoder',
  'GPUComputePassTimestampWrites', 'GPUComputePipeline',
  'GPUComputePipelineDescriptor', 'GPUCopyExternalImageDestInfo',
  'GPUCopyExternalImageSource', 'GPUCopyExternalImageSourceInfo',
  'GPUCullMode', 'GPUDebugCommandsMixin', 'GPUDepthBias',
  'GPUDepthStencilState', 'GPUDevice', 'GPUDeviceDescriptor',
  'GPUDeviceEventMap', 'GPUDeviceLostInfo', 'GPUDeviceLostReason', 'GPUError',
  'GPUErrorFilter', 'GPUExtent3D', 'GPUExtent3DDict', 'GPUExternalTexture',
  'GPUExternalTextureBindingLayout', 'GPUExternalTextureDescriptor',
  'GPUFeatureName', 'GPUFilterMode', 'GPUFlagsConstant', 'GPUFragmentState',
  'GPUFrontFace', 'GPUIndex32', 'GPUIndexFormat', 'GPUIntegerCoordinate',
  'GPUIntegerCoordinateOut', 'GPUInternalError', 'GPULoadOp',
  'GPUMapModeFlags', 'GPUMipmapFilterMode', 'GPUMultisampleState',
  'GPUObjectBase', 'GPUObjectDescriptorBase', 'GPUOrigin2D',
  'GPUOrigin2DDict', 'GPUOrigin3D', 'GPUOrigin3DDict', 'GPUOutOfMemoryError',
  'GPUPipelineBase', 'GPUPipelineConstantValue', 'GPUPipelineDescriptorBase',
  'GPUPipelineError', 'GPUPipelineErrorInit', 'GPUPipelineErrorReason',
  'GPUPipelineLayout', 'GPUPipelineLayoutDescriptor', 'GPUPowerPreference',
  'GPUPrimitiveState', 'GPUPrimitiveTopology', 'GPUProgrammableStage',
  'GPUQuerySet', 'GPUQuerySetDescriptor', 'GPUQueryType', 'GPUQueue',
  'GPUQueueDescriptor', 'GPURenderBundle', 'GPURenderBundleDescriptor',
  'GPURenderBundleEncoder', 'GPURenderBundleEncoderDescriptor',
  'GPURenderCommandsMixin', 'GPURenderPassColorAttachment',
  'GPURenderPassDepthStencilAttachment', 'GPURenderPassDescriptor',
  'GPURenderPassEncoder', 'GPURenderPassLayout',
  'GPURenderPassTimestampWrites', 'GPURenderPipeline',
  'GPURenderPipelineDescriptor', 'GPURequestAdapterOptions', 'GPUSampleMask',
  'GPUSampler', 'GPUSamplerBindingLayout', 'GPUSamplerBindingType',
  'GPUSamplerDescriptor', 'GPUShaderModule', 'GPUShaderModuleDescriptor',
  'GPUShaderStageFlags', 'GPUSignedOffset32', 'GPUSize32', 'GPUSize32Out',
  'GPUSize64', 'GPUSize64Out', 'GPUStencilFaceState', 'GPUStencilOperation',
  'GPUStencilValue', 'GPUStorageTextureAccess',
  'GPUStorageTextureBindingLayout', 'GPUStoreOp', 'GPUSupportedFeatures',
  'GPUSupportedLimits', 'GPUTexelCopyBufferInfo', 'GPUTexelCopyBufferLayout',
  'GPUTexelCopyTextureInfo', 'GPUTexture', 'GPUTextureAspect',
  'GPUTextureBindingLayout', 'GPUTextureDescriptor', 'GPUTextureDimension',
  'GPUTextureFormat', 'GPUTextureSampleType', 'GPUTextureUsageFlags',
  'GPUTextureView', 'GPUTextureViewDescriptor', 'GPUTextureViewDimension',
  'GPUUncapturedErrorEvent', 'GPUUncapturedErrorEventInit',
  'GPUValidationError', 'GPUVertexAttribute', 'GPUVertexBufferLayout',
  'GPUVertexFormat', 'GPUVertexState', 'GPUVertexStepMode', 'GainNode',
  'GainOptions', 'Gamepad', 'GamepadButton', 'GamepadEffectParameters',
  'GamepadEvent', 'GamepadEventInit', 'GamepadHapticActuator',
  'GamepadHapticEffectType', 'GamepadHapticsResult', 'GamepadMappingType',
  'Generator', 'GeneratorFunction', 'GeneratorFunctionConstructor',
  'GenericTransformStream', 'Geolocation', 'GeolocationCoordinates',
  'GeolocationPosition', 'GeolocationPositionError', 'GetAnimationsOptions',
  'GetComposedRangesOptions', 'GetHTMLOptions', 'GetNotificationOptions',
  'GetRootNodeOptions', 'Global', 'GlobalCompositeOperation',
  'GlobalDescriptor', 'GlobalEventHandlers', 'GlobalEventHandlersEventMap',
  'HTMLAllCollection', 'HTMLAnchorElement', 'HTMLAreaElement',
  'HTMLAudioElement', 'HTMLBRElement', 'HTMLBaseElement', 'HTMLBodyElement',
  'HTMLBodyElementEventMap', 'HTMLButtonElement', 'HTMLCanvasElement',
  'HTMLCollection', 'HTMLCollectionBase', 'HTMLCollectionOf',
  'HTMLDListElement', 'HTMLDataElement', 'HTMLDataListElement',
  'HTMLDetailsElement', 'HTMLDialogElement', 'HTMLDirectoryElement',
  'HTMLDivElement', 'HTMLDocument', 'HTMLElement',
  'HTMLElementDeprecatedTagNameMap', 'HTMLElementEventMap',
  'HTMLElementTagNameMap', 'HTMLEmbedElement', 'HTMLFieldSetElement',
  'HTMLFontElement', 'HTMLFormControlsCollection', 'HTMLFormElement',
  'HTMLFrameElement', 'HTMLFrameSetElement', 'HTMLFrameSetElementEventMap',
  'HTMLHRElement', 'HTMLHeadElement', 'HTMLHeadingElement', 'HTMLHtmlElement',
  'HTMLHyperlinkElementUtils', 'HTMLIFrameElement', 'HTMLImageElement',
  'HTMLInputElement', 'HTMLLIElement', 'HTMLLabelElement',
  'HTMLLegendElement', 'HTMLLinkElement', 'HTMLMapElement',
  'HTMLMarqueeElement', 'HTMLMediaElement', 'HTMLMediaElementEventMap',
  'HTMLMenuElement', 'HTMLMetaElement', 'HTMLMeterElement', 'HTMLModElement',
  'HTMLOListElement', 'HTMLObjectElement', 'HTMLOptGroupElement',
  'HTMLOptionElement', 'HTMLOptionsCollection', 'HTMLOrSVGElement',
  'HTMLOrSVGImageElement', 'HTMLOrSVGScriptElement', 'HTMLOutputElement',
  'HTMLParagraphElement', 'HTMLParamElement', 'HTMLPictureElement',
  'HTMLPreElement', 'HTMLProgressElement', 'HTMLQuoteElement',
  'HTMLScriptElement', 'HTMLSelectElement', 'HTMLSlotElement',
  'HTMLSourceElement', 'HTMLSpanElement', 'HTMLStyleElement',
  'HTMLTableCaptionElement', 'HTMLTableCellElement', 'HTMLTableColElement',
  'HTMLTableDataCellElement', 'HTMLTableElement',
  'HTMLTableHeaderCellElement', 'HTMLTableRowElement',
  'HTMLTableSectionElement', 'HTMLTemplateElement', 'HTMLTextAreaElement',
  'HTMLTimeElement', 'HTMLTitleElement', 'HTMLTrackElement',
  'HTMLUListElement', 'HTMLUnknownElement', 'HTMLVideoElement',
  'HTMLVideoElementEventMap', 'HardwareAcceleration',
  'HashAlgorithmIdentifier', 'HashChangeEvent', 'HashChangeEventInit',
  'HdrMetadataType', 'Headers', 'HeadersInit', 'HeadersIterator', 'Highlight',
  'HighlightRegistry', 'HighlightType', 'History', 'HkdfParams',
  'HmacImportParams', 'HmacKeyAlgorithm', 'HmacKeyGenParams', 'IArguments',
  'IDBCursor', 'IDBCursorDirection', 'IDBCursorWithValue', 'IDBDatabase',
  'IDBDatabaseEventMap', 'IDBDatabaseInfo', 'IDBFactory', 'IDBIndex',
  'IDBIndexParameters', 'IDBKeyRange', 'IDBObjectStore',
  'IDBObjectStoreParameters', 'IDBOpenDBRequest', 'IDBOpenDBRequestEventMap',
  'IDBRequest', 'IDBRequestEventMap', 'IDBRequestReadyState',
  'IDBTransaction', 'IDBTransactionDurability', 'IDBTransactionEventMap',
  'IDBTransactionMode', 'IDBTransactionOptions', 'IDBValidKey',
  'IDBVersionChangeEvent', 'IDBVersionChangeEventInit', 'IIRFilterNode',
  'IIRFilterOptions', 'ITextWriter', 'IdleDeadline', 'IdleRequestCallback',
  'IdleRequestOptions', 'Image', 'ImageBitmap', 'ImageBitmapOptions',
  'ImageBitmapRenderingContext', 'ImageBitmapRenderingContextSettings',
  'ImageBitmapSource', 'ImageBufferSource', 'ImageCapture', 'ImageData',
  'ImageDataArray', 'ImageDataPixelFormat', 'ImageDataSettings',
  'ImageDecodeOptions', 'ImageDecodeResult', 'ImageDecoder',
  'ImageDecoderInit', 'ImageEncodeOptions', 'ImageOrientation',
  'ImageSmoothingQuality', 'ImageTrack', 'ImageTrackList', 'Immediate',
  'ImportAssertions', 'ImportAttributes', 'ImportCallOptions',
  'ImportExportKind', 'ImportMeta', 'ImportNodeOptions', 'ImportValue',
  'Imports', 'Infinity', 'InputDeviceInfo', 'InputEvent', 'InputEventInit',
  'InsertPosition', 'Instance', 'InstanceType', 'Instant',
  'InstantConstructor', 'InstantLike', 'InstantToStringOptions', 'Int16Array',
  'Int16ArrayConstructor', 'Int32Array', 'Int32ArrayConstructor', 'Int32List',
  'Int8Array', 'Int8ArrayConstructor', 'IntersectionObserver',
  'IntersectionObserverCallback', 'IntersectionObserverEntry',
  'IntersectionObserverInit', 'Intl', 'Iterable', 'IterableIterator',
  'IterationCompositeOperation', 'Iterator', 'IteratorConstructor',
  'IteratorObject', 'IteratorObjectConstructor', 'IteratorResult',
  'IteratorReturnResult', 'IteratorYieldResult', 'JSON', 'JsonWebKey',
  'KHR_parallel_shader_compile', 'KeyAlgorithm', 'KeyFormat',
  'KeySystemTrackConfiguration', 'KeyType', 'KeyUsage', 'KeyboardEvent',
  'KeyboardEventInit', 'Keyframe', 'KeyframeAnimationOptions',
  'KeyframeEffect', 'KeyframeEffectOptions', 'LDMLPluralRule',
  'LargestContentfulPaint', 'LatencyMode', 'LineAlignSetting',
  'LineAndPositionSetting', 'LinkError', 'LinkStyle', 'ListFormat',
  'ListFormatLocaleMatcher', 'ListFormatOptions', 'ListFormatStyle',
  'ListFormatType', 'Locale', 'LocaleCollationCaseFirst',
  'LocaleHourCycleKey', 'LocaleOptions', 'LocalesArgument', 'Location',
  'Lock', 'LockGrantedCallback', 'LockInfo', 'LockManager',
  'LockManagerSnapshot', 'LockMode', 'LockOptions', 'LoginStatus',
  'Lowercase', 'MIDIAccess', 'MIDIAccessEventMap', 'MIDIConnectionEvent',
  'MIDIConnectionEventInit', 'MIDIInput', 'MIDIInputEventMap', 'MIDIInputMap',
  'MIDIMessageEvent', 'MIDIMessageEventInit', 'MIDIOptions', 'MIDIOutput',
  'MIDIOutputMap', 'MIDIPort', 'MIDIPortConnectionState',
  'MIDIPortDeviceState', 'MIDIPortEventMap', 'MIDIPortType', 'Map',
  'MapConstructor', 'MapIterator', 'Math', 'MathMLElement',
  'MathMLElementEventMap', 'MathMLElementTagNameMap', 'MediaCapabilities',
  'MediaCapabilitiesDecodingInfo', 'MediaCapabilitiesEncodingInfo',
  'MediaCapabilitiesInfo', 'MediaCapabilitiesKeySystemConfiguration',
  'MediaConfiguration', 'MediaDecodingConfiguration', 'MediaDecodingType',
  'MediaDeviceInfo', 'MediaDeviceKind', 'MediaDevices',
  'MediaDevicesEventMap', 'MediaElementAudioSourceNode',
  'MediaElementAudioSourceOptions', 'MediaEncodingConfiguration',
  'MediaEncodingType', 'MediaEncryptedEvent', 'MediaEncryptedEventInit',
  'MediaError', 'MediaImage', 'MediaKeyMessageEvent',
  'MediaKeyMessageEventInit', 'MediaKeyMessageType', 'MediaKeySession',
  'MediaKeySessionClosedReason', 'MediaKeySessionEventMap',
  'MediaKeySessionType', 'MediaKeyStatus', 'MediaKeyStatusMap',
  'MediaKeyStatusMapIterator', 'MediaKeySystemAccess',
  'MediaKeySystemConfiguration', 'MediaKeySystemMediaCapability', 'MediaKeys',
  'MediaKeysPolicy', 'MediaKeysRequirement', 'MediaList', 'MediaMetadata',
  'MediaMetadataInit', 'MediaPositionState', 'MediaProvider',
  'MediaQueryList', 'MediaQueryListEvent', 'MediaQueryListEventInit',
  'MediaQueryListEventMap', 'MediaRecorder', 'MediaRecorderEventMap',
  'MediaRecorderOptions', 'MediaSession', 'MediaSessionAction',
  'MediaSessionActionDetails', 'MediaSessionActionHandler',
  'MediaSessionPlaybackState', 'MediaSettingsRange', 'MediaSource',
  'MediaSourceEventMap', 'MediaSourceHandle', 'MediaStream',
  'MediaStreamAudioDestinationNode', 'MediaStreamAudioSourceNode',
  'MediaStreamAudioSourceOptions', 'MediaStreamConstraints',
  'MediaStreamEventMap', 'MediaStreamTrack', 'MediaStreamTrackEvent',
  'MediaStreamTrackEventInit', 'MediaStreamTrackEventMap',
  'MediaStreamTrackProcessor', 'MediaStreamTrackProcessorInit',
  'MediaStreamTrackState', 'MediaTrackCapabilities',
  'MediaTrackConstraintSet', 'MediaTrackConstraints', 'MediaTrackSettings',
  'MediaTrackSupportedConstraints', 'Memory', 'MemoryDescriptor',
  'MessageChannel', 'MessageEvent', 'MessageEventInit', 'MessageEventSource',
  'MessageEventTarget', 'MessageEventTargetEventMap', 'MessagePort',
  'MessagePortEventMap', 'MethodDecorator', 'MimeType', 'MimeTypeArray',
  'Module', 'ModuleExportDescriptor', 'ModuleImportDescriptor',
  'ModuleImports', 'MouseEvent', 'MouseEventInit', 'MultiCacheQueryOptions',
  'MutationCallback', 'MutationObserver', 'MutationObserverInit',
  'MutationRecord', 'MutationRecordType', 'NaN', 'NamedCurve', 'NamedNodeMap',
  'NavigateEvent', 'NavigateEventInit', 'Navigation', 'NavigationActivation',
  'NavigationCurrentEntryChangeEvent',
  'NavigationCurrentEntryChangeEventInit', 'NavigationDestination',
  'NavigationEventMap', 'NavigationFocusReset', 'NavigationHistoryBehavior',
  'NavigationHistoryEntry', 'NavigationHistoryEntryEventMap',
  'NavigationInterceptHandler', 'NavigationInterceptOptions',
  'NavigationNavigateOptions', 'NavigationOptions',
  'NavigationPrecommitController', 'NavigationPrecommitHandler',
  'NavigationPreloadManager', 'NavigationPreloadState',
  'NavigationReloadOptions', 'NavigationResult', 'NavigationScrollBehavior',
  'NavigationTimingType', 'NavigationTransition', 'NavigationType',
  'NavigationUpdateCurrentEntryOptions', 'Navigator',
  'NavigatorAutomationInformation', 'NavigatorBadge',
  'NavigatorConcurrentHardware', 'NavigatorContentUtils', 'NavigatorCookies',
  'NavigatorGPU', 'NavigatorID', 'NavigatorLanguage', 'NavigatorLocks',
  'NavigatorLogin', 'NavigatorOnLine', 'NavigatorPlugins', 'NavigatorStorage',
  'NewableFunction', 'NoInfer', 'Node', 'NodeFilter', 'NodeIterator',
  'NodeJS', 'NodeList', 'NodeListOf', 'NodeModule', 'NodeRequire',
  'NonDocumentTypeChildNode', 'NonElementParentNode', 'NonNullable',
  'Notification', 'NotificationDirection', 'NotificationEvent',
  'NotificationEventInit', 'NotificationEventMap', 'NotificationOptions',
  'NotificationPermission', 'NotificationPermissionCallback', 'Now', 'Number',
  'NumberConstructor', 'NumberFormat', 'NumberFormatConstructor',
  'NumberFormatOptions', 'NumberFormatOptionsCurrencyDisplay',
  'NumberFormatOptionsCurrencyDisplayRegistry',
  'NumberFormatOptionsSignDisplay', 'NumberFormatOptionsSignDisplayRegistry',
  'NumberFormatOptionsStyle', 'NumberFormatOptionsStyleRegistry',
  'NumberFormatOptionsUseGrouping', 'NumberFormatOptionsUseGroupingRegistry',
  'NumberFormatPart', 'NumberFormatPartTypeRegistry', 'NumberFormatPartTypes',
  'NumberFormatRangePartTypeRegistry', 'NumberFormatRangePartTypes',
  'NumberRangeFormatPart', 'OES_draw_buffers_indexed',
  'OES_element_index_uint', 'OES_fbo_render_mipmap',
  'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear',
  'OES_texture_half_float', 'OES_texture_half_float_linear',
  'OES_vertex_array_object', 'OVR_multiview2', 'Object', 'ObjectConstructor',
  'OfflineAudioCompletionEvent', 'OfflineAudioCompletionEventInit',
  'OfflineAudioContext', 'OfflineAudioContextEventMap',
  'OfflineAudioContextOptions', 'OffscreenCanvas', 'OffscreenCanvasEventMap',
  'OffscreenCanvasRenderingContext2D', 'OffscreenRenderingContext',
  'OffscreenRenderingContextId', 'Omit', 'OmitThisParameter',
  'OnBeforeUnloadEventHandler', 'OnBeforeUnloadEventHandlerNonNull',
  'OnErrorEventHandler', 'OnErrorEventHandlerNonNull', 'Option',
  'OptionalEffectTiming', 'OptionalPostfixToken', 'OptionalPrefixToken',
  'OpusBitstreamFormat', 'OpusEncoderConfig', 'OrientationLockType',
  'OrientationType', 'OscillatorNode', 'OscillatorOptions', 'OscillatorType',
  'OverSampleType', 'OverconstrainedError', 'OverflowOptions',
  'PageRevealEvent', 'PageRevealEventInit', 'PageSwapEvent',
  'PageSwapEventInit', 'PageTransitionEvent', 'PageTransitionEventInit',
  'PaintTimingMixin', 'PannerNode', 'PannerOptions', 'PanningModelType',
  'ParameterDecorator', 'Parameters', 'ParentNode', 'Partial',
  'PartialTemporalLike', 'Path2D', 'PayerErrors', 'PaymentAddress',
  'PaymentComplete', 'PaymentCurrencyAmount', 'PaymentDetailsBase',
  'PaymentDetailsInit', 'PaymentDetailsModifier', 'PaymentDetailsUpdate',
  'PaymentItem', 'PaymentMethodChangeEvent', 'PaymentMethodChangeEventInit',
  'PaymentMethodData', 'PaymentOptions', 'PaymentRequest',
  'PaymentRequestEventMap', 'PaymentRequestUpdateEvent',
  'PaymentRequestUpdateEventInit', 'PaymentResponse',
  'PaymentResponseEventMap', 'PaymentShippingOption', 'PaymentShippingType',
  'PaymentValidationErrors', 'Pbkdf2Params', 'Performance',
  'PerformanceEntry', 'PerformanceEntryList', 'PerformanceEventMap',
  'PerformanceEventTiming', 'PerformanceMark', 'PerformanceMarkOptions',
  'PerformanceMeasure', 'PerformanceMeasureOptions', 'PerformanceNavigation',
  'PerformanceNavigationTiming', 'PerformanceObserver',
  'PerformanceObserverCallback', 'PerformanceObserverEntryList',
  'PerformanceObserverInit', 'PerformancePaintTiming',
  'PerformanceResourceTiming', 'PerformanceServerTiming', 'PerformanceTiming',
  'PeriodicWave', 'PeriodicWaveConstraints', 'PeriodicWaveOptions',
  'PermissionDescriptor', 'PermissionName', 'PermissionState',
  'PermissionStatus', 'PermissionStatusEventMap', 'Permissions',
  'PhotoCapabilities', 'PhotoSettings', 'Pick', 'PictureInPictureEvent',
  'PictureInPictureEventInit', 'PictureInPictureWindow',
  'PictureInPictureWindowEventMap', 'PlainDate', 'PlainDateConstructor',
  'PlainDateLike', 'PlainDateTime', 'PlainDateTimeConstructor',
  'PlainDateTimeLike', 'PlainDateTimeToStringOptions',
  'PlainDateToStringOptions', 'PlainDateToZonedDateTimeOptions',
  'PlainMonthDay', 'PlainMonthDayConstructor', 'PlainMonthDayLike',
  'PlainMonthDayToPlainDateOptions', 'PlainTime', 'PlainTimeConstructor',
  'PlainTimeLike', 'PlainTimeToStringOptions', 'PlainYearMonth',
  'PlainYearMonthConstructor', 'PlainYearMonthLike',
  'PlainYearMonthToPlainDateOptions', 'PlaneLayout', 'PlaybackDirection',
  'Plugin', 'PluginArray', 'PluralRuleType', 'PluralRules',
  'PluralRulesConstructor', 'PluralRulesOptions', 'PluralizeUnit',
  'PointerEvent', 'PointerEventInit', 'PointerLockOptions', 'PopStateEvent',
  'PopStateEventInit', 'PopoverTargetAttributes', 'PositionAlignSetting',
  'PositionCallback', 'PositionErrorCallback', 'PositionOptions',
  'PredefinedColorSpace', 'PremultiplyAlpha', 'PresentationStyle',
  'ProcessingInstruction', 'ProgressEvent', 'ProgressEventInit', 'Promise',
  'PromiseConstructor', 'PromiseConstructorLike', 'PromiseFulfilledResult',
  'PromiseLike', 'PromiseRejectedResult', 'PromiseRejectionEvent',
  'PromiseRejectionEventInit', 'PromiseSettledResult', 'PromiseWithResolvers',
  'PropertyDecorator', 'PropertyDefinition', 'PropertyDescriptor',
  'PropertyDescriptorMap', 'PropertyIndexedKeyframes', 'PropertyKey', 'Proxy',
  'ProxyConstructor', 'ProxyHandler', 'PublicKeyCredential',
  'PublicKeyCredentialClientCapabilities',
  'PublicKeyCredentialCreationOptions',
  'PublicKeyCredentialCreationOptionsJSON', 'PublicKeyCredentialDescriptor',
  'PublicKeyCredentialDescriptorJSON', 'PublicKeyCredentialEntity',
  'PublicKeyCredentialParameters', 'PublicKeyCredentialRequestOptions',
  'PublicKeyCredentialRequestOptionsJSON', 'PublicKeyCredentialRpEntity',
  'PublicKeyCredentialType', 'PublicKeyCredentialUserEntity',
  'PublicKeyCredentialUserEntityJSON', 'PushEncryptionKeyName', 'PushEvent',
  'PushEventInit', 'PushManager', 'PushManagerAttribute', 'PushMessageData',
  'PushMessageDataInit', 'PushSubscription', 'PushSubscriptionChangeEvent',
  'PushSubscriptionChangeEventInit', 'PushSubscriptionJSON',
  'PushSubscriptionOptions', 'PushSubscriptionOptionsInit', 'QueuingStrategy',
  'QueuingStrategyInit', 'QueuingStrategySize', 'RTCAnswerOptions',
  'RTCBundlePolicy', 'RTCCertificate', 'RTCCertificateExpiration',
  'RTCConfiguration', 'RTCDTMFSender', 'RTCDTMFSenderEventMap',
  'RTCDTMFToneChangeEvent', 'RTCDTMFToneChangeEventInit', 'RTCDataChannel',
  'RTCDataChannelEvent', 'RTCDataChannelEventInit', 'RTCDataChannelEventMap',
  'RTCDataChannelInit', 'RTCDataChannelState', 'RTCDegradationPreference',
  'RTCDtlsFingerprint', 'RTCDtlsRole', 'RTCDtlsTransport',
  'RTCDtlsTransportEventMap', 'RTCDtlsTransportState', 'RTCEncodedAudioFrame',
  'RTCEncodedAudioFrameMetadata', 'RTCEncodedFrameMetadata',
  'RTCEncodedVideoFrame', 'RTCEncodedVideoFrameMetadata', 'RTCError',
  'RTCErrorDetailType', 'RTCErrorEvent', 'RTCErrorEventInit', 'RTCErrorInit',
  'RTCIceCandidate', 'RTCIceCandidateInit', 'RTCIceCandidatePair',
  'RTCIceCandidatePairStats', 'RTCIceCandidateType', 'RTCIceComponent',
  'RTCIceConnectionState', 'RTCIceGathererState', 'RTCIceGatheringState',
  'RTCIceProtocol', 'RTCIceRole', 'RTCIceServer', 'RTCIceTcpCandidateType',
  'RTCIceTransport', 'RTCIceTransportEventMap', 'RTCIceTransportPolicy',
  'RTCIceTransportState', 'RTCInboundRtpStreamStats',
  'RTCLocalIceCandidateInit', 'RTCLocalSessionDescriptionInit',
  'RTCOfferAnswerOptions', 'RTCOfferOptions', 'RTCOutboundRtpStreamStats',
  'RTCPeerConnection', 'RTCPeerConnectionErrorCallback',
  'RTCPeerConnectionEventMap', 'RTCPeerConnectionIceErrorEvent',
  'RTCPeerConnectionIceErrorEventInit', 'RTCPeerConnectionIceEvent',
  'RTCPeerConnectionIceEventInit', 'RTCPeerConnectionState',
  'RTCPriorityType', 'RTCQualityLimitationReason',
  'RTCReceivedRtpStreamStats', 'RTCRtcpMuxPolicy', 'RTCRtcpParameters',
  'RTCRtpCapabilities', 'RTCRtpCodec', 'RTCRtpCodecParameters',
  'RTCRtpCodingParameters', 'RTCRtpContributingSource',
  'RTCRtpEncodingParameters', 'RTCRtpHeaderExtensionCapability',
  'RTCRtpHeaderExtensionParameters', 'RTCRtpParameters',
  'RTCRtpReceiveParameters', 'RTCRtpReceiver', 'RTCRtpReceiverTransform',
  'RTCRtpScriptTransform', 'RTCRtpScriptTransformer', 'RTCRtpSendParameters',
  'RTCRtpSender', 'RTCRtpSenderTransform', 'RTCRtpStreamStats',
  'RTCRtpSynchronizationSource', 'RTCRtpTransceiver',
  'RTCRtpTransceiverDirection', 'RTCRtpTransceiverInit', 'RTCSctpTransport',
  'RTCSctpTransportEventMap', 'RTCSctpTransportState', 'RTCSdpType',
  'RTCSentRtpStreamStats', 'RTCSessionDescription',
  'RTCSessionDescriptionCallback', 'RTCSessionDescriptionInit',
  'RTCSetParameterOptions', 'RTCSignalingState', 'RTCStats',
  'RTCStatsIceCandidatePairState', 'RTCStatsReport', 'RTCStatsType',
  'RTCTrackEvent', 'RTCTrackEventInit', 'RTCTransformEvent',
  'RTCTransportStats', 'RadioNodeList', 'Range', 'RangeError',
  'RangeErrorConstructor', 'ReadableByteStreamController', 'ReadableStream',
  'ReadableStreamAsyncIterator', 'ReadableStreamBYOBReader',
  'ReadableStreamBYOBReaderReadOptions', 'ReadableStreamBYOBRequest',
  'ReadableStreamController', 'ReadableStreamDefaultController',
  'ReadableStreamDefaultReader', 'ReadableStreamGenericReader',
  'ReadableStreamGetReaderOptions', 'ReadableStreamIteratorOptions',
  'ReadableStreamReadDoneResult', 'ReadableStreamReadResult',
  'ReadableStreamReadValueResult', 'ReadableStreamReader',
  'ReadableStreamReaderMode', 'ReadableStreamType', 'ReadableWritablePair',
  'Readonly', 'ReadonlyArray', 'ReadonlyMap', 'ReadonlySet',
  'ReadonlySetLike', 'ReadyState', 'Record', 'RecordingState',
  'RedEyeReduction', 'ReferenceError', 'ReferenceErrorConstructor',
  'ReferrerPolicy', 'Reflect', 'RegExp', 'RegExpConstructor',
  'RegExpExecArray', 'RegExpIndicesArray', 'RegExpMatchArray',
  'RegExpStringIterator', 'RegistrationOptions', 'RegistrationResponseJSON',
  'RelativeTimeFormat', 'RelativeTimeFormatLocaleMatcher',
  'RelativeTimeFormatNumeric', 'RelativeTimeFormatOptions',
  'RelativeTimeFormatPart', 'RelativeTimeFormatStyle',
  'RelativeTimeFormatUnit', 'RelativeTimeFormatUnitSingular',
  'RemotePlayback', 'RemotePlaybackAvailabilityCallback',
  'RemotePlaybackEventMap', 'RemotePlaybackState', 'RenderingContext',
  'Report', 'ReportBody', 'ReportList', 'ReportingObserver',
  'ReportingObserverCallback', 'ReportingObserverOptions', 'Request',
  'RequestCache', 'RequestCredentials', 'RequestDestination', 'RequestInfo',
  'RequestInit', 'RequestMode', 'RequestPriority', 'RequestRedirect',
  'Required', 'ResidentKeyRequirement', 'ResizeObserver',
  'ResizeObserverBoxOptions', 'ResizeObserverCallback', 'ResizeObserverEntry',
  'ResizeObserverOptions', 'ResizeObserverSize', 'ResizeQuality',
  'ResolvedCollatorOptions', 'ResolvedDateTimeFormatOptions',
  'ResolvedDisplayNamesOptions', 'ResolvedDurationFormatOptions',
  'ResolvedListFormatOptions', 'ResolvedNumberFormatOptions',
  'ResolvedNumberFormatOptionsUseGrouping', 'ResolvedPluralRulesOptions',
  'ResolvedRelativeTimeFormatOptions', 'ResolvedSegmenterOptions', 'Response',
  'ResponseInit', 'ResponseType', 'ReturnType', 'RoundingOptions',
  'RoundingOptionsWithLargestUnit', 'RsaHashedImportParams',
  'RsaHashedKeyAlgorithm', 'RsaHashedKeyGenParams', 'RsaKeyAlgorithm',
  'RsaKeyGenParams', 'RsaOaepParams', 'RsaOtherPrimesInfo', 'RsaPssParams',
  'RuntimeError', 'SVGAElement', 'SVGAngle', 'SVGAnimateElement',
  'SVGAnimateMotionElement', 'SVGAnimateTransformElement', 'SVGAnimatedAngle',
  'SVGAnimatedBoolean', 'SVGAnimatedEnumeration', 'SVGAnimatedInteger',
  'SVGAnimatedLength', 'SVGAnimatedLengthList', 'SVGAnimatedNumber',
  'SVGAnimatedNumberList', 'SVGAnimatedPoints',
  'SVGAnimatedPreserveAspectRatio', 'SVGAnimatedRect', 'SVGAnimatedString',
  'SVGAnimatedTransformList', 'SVGAnimationElement', 'SVGBoundingBoxOptions',
  'SVGCircleElement', 'SVGClipPathElement',
  'SVGComponentTransferFunctionElement', 'SVGDefsElement', 'SVGDescElement',
  'SVGElement', 'SVGElementEventMap', 'SVGElementTagNameMap',
  'SVGEllipseElement', 'SVGFEBlendElement', 'SVGFEColorMatrixElement',
  'SVGFEComponentTransferElement', 'SVGFECompositeElement',
  'SVGFEConvolveMatrixElement', 'SVGFEDiffuseLightingElement',
  'SVGFEDisplacementMapElement', 'SVGFEDistantLightElement',
  'SVGFEDropShadowElement', 'SVGFEFloodElement', 'SVGFEFuncAElement',
  'SVGFEFuncBElement', 'SVGFEFuncGElement', 'SVGFEFuncRElement',
  'SVGFEGaussianBlurElement', 'SVGFEImageElement', 'SVGFEMergeElement',
  'SVGFEMergeNodeElement', 'SVGFEMorphologyElement', 'SVGFEOffsetElement',
  'SVGFEPointLightElement', 'SVGFESpecularLightingElement',
  'SVGFESpotLightElement', 'SVGFETileElement', 'SVGFETurbulenceElement',
  'SVGFilterElement', 'SVGFilterPrimitiveStandardAttributes',
  'SVGFitToViewBox', 'SVGForeignObjectElement', 'SVGGElement',
  'SVGGeometryElement', 'SVGGradientElement', 'SVGGraphicsElement',
  'SVGImageElement', 'SVGLength', 'SVGLengthList', 'SVGLineElement',
  'SVGLinearGradientElement', 'SVGMPathElement', 'SVGMarkerElement',
  'SVGMaskElement', 'SVGMatrix', 'SVGMetadataElement', 'SVGNumber',
  'SVGNumberList', 'SVGPathElement', 'SVGPatternElement', 'SVGPoint',
  'SVGPointList', 'SVGPolygonElement', 'SVGPolylineElement',
  'SVGPreserveAspectRatio', 'SVGRadialGradientElement', 'SVGRect',
  'SVGRectElement', 'SVGSVGElement', 'SVGSVGElementEventMap',
  'SVGScriptElement', 'SVGSetElement', 'SVGStopElement', 'SVGStringList',
  'SVGStyleElement', 'SVGSwitchElement', 'SVGSymbolElement',
  'SVGTSpanElement', 'SVGTests', 'SVGTextContentElement', 'SVGTextElement',
  'SVGTextPathElement', 'SVGTextPositioningElement', 'SVGTitleElement',
  'SVGTransform', 'SVGTransformList', 'SVGURIReference', 'SVGUnitTypes',
  'SVGUseElement', 'SVGViewElement', 'Sanitizer', 'SanitizerAttribute',
  'SanitizerAttributeNamespace', 'SanitizerConfig', 'SanitizerElement',
  'SanitizerElementNamespace', 'SanitizerElementNamespaceWithAttributes',
  'SanitizerElementWithAttributes', 'SanitizerPresets', 'Scheduler',
  'SchedulerPostTaskCallback', 'SchedulerPostTaskOptions', 'Screen',
  'ScreenOrientation', 'ScreenOrientationEventMap', 'ScriptProcessorNode',
  'ScriptProcessorNodeEventMap', 'ScrollAxis', 'ScrollBehavior',
  'ScrollIntoViewOptions', 'ScrollLogicalPosition', 'ScrollOptions',
  'ScrollRestoration', 'ScrollSetting', 'ScrollTimeline',
  'ScrollTimelineOptions', 'ScrollToOptions', 'SecurityPolicyViolationEvent',
  'SecurityPolicyViolationEventDisposition',
  'SecurityPolicyViolationEventInit', 'SegmentData', 'SegmentIterator',
  'Segmenter', 'SegmenterOptions', 'Segments', 'Selection',
  'SelectionDirection', 'SelectionMode', 'Server', 'ServerWebSocket',
  'ServiceWorker', 'ServiceWorkerContainer', 'ServiceWorkerContainerEventMap',
  'ServiceWorkerEventMap', 'ServiceWorkerGlobalScope',
  'ServiceWorkerGlobalScopeEventMap', 'ServiceWorkerRegistration',
  'ServiceWorkerRegistrationEventMap', 'ServiceWorkerState',
  'ServiceWorkerUpdateViaCache', 'Set', 'SetConstructor', 'SetIterator',
  'ShadowRoot', 'ShadowRootEventMap', 'ShadowRootInit', 'ShadowRootMode',
  'ShareData', 'SharedArrayBuffer', 'SharedArrayBufferConstructor',
  'SharedWorker', 'SharedWorkerGlobalScope',
  'SharedWorkerGlobalScopeEventMap', 'ShellPromise', 'ShowPopoverOptions',
  'SlotAssignmentMode', 'Slottable', 'Socket', 'SocketHandler',
  'SourceBuffer', 'SourceBufferEventMap', 'SourceBufferList',
  'SourceBufferListEventMap', 'SpeechRecognitionAlternative',
  'SpeechRecognitionErrorCode', 'SpeechRecognitionErrorEvent',
  'SpeechRecognitionErrorEventInit', 'SpeechRecognitionEvent',
  'SpeechRecognitionEventInit', 'SpeechRecognitionResult',
  'SpeechRecognitionResultList', 'SpeechSynthesis',
  'SpeechSynthesisErrorCode', 'SpeechSynthesisErrorEvent',
  'SpeechSynthesisErrorEventInit', 'SpeechSynthesisEvent',
  'SpeechSynthesisEventInit', 'SpeechSynthesisEventMap',
  'SpeechSynthesisUtterance', 'SpeechSynthesisUtteranceEventMap',
  'SpeechSynthesisVoice', 'StartViewTransitionOptions', 'StaticRange',
  'StaticRangeInit', 'Stats', 'StereoPannerNode', 'StereoPannerOptions',
  'Storage', 'StorageEstimate', 'StorageEvent', 'StorageEventInit',
  'StorageManager', 'StreamPipeOptions', 'String', 'StringConstructor',
  'StringIterator', 'StringNumericLiteral', 'StructuredSerializeOptions',
  'StylePropertyMap', 'StylePropertyMapReadOnly',
  'StylePropertyMapReadOnlyIterator', 'StyleSheet', 'StyleSheetList',
  'SubmitEvent', 'SubmitEventInit', 'Subprocess', 'SubtleCrypto',
  'SuppressedError', 'SuppressedErrorConstructor', 'SvcOutputMetadata',
  'Symbol', 'SymbolConstructor', 'SyntaxError', 'SyntaxErrorConstructor',
  'TCPSocket', 'Table', 'TableDescriptor', 'TableKind', 'Tag', 'TagType',
  'TaskController', 'TaskControllerInit', 'TaskPriority',
  'TaskPriorityChangeEvent', 'TaskPriorityChangeEventInit', 'TaskSignal',
  'TaskSignalAnyInit', 'TaskSignalEventMap', 'TemplateStringsArray',
  'Temporal', 'TexImageSource', 'Text', 'TextDecodeOptions', 'TextDecoder',
  'TextDecoderCommon', 'TextDecoderOptions', 'TextDecoderStream',
  'TextEncoder', 'TextEncoderCommon', 'TextEncoderEncodeIntoResult',
  'TextEncoderStream', 'TextEvent', 'TextInfo', 'TextMetrics',
  'TextStreamBase', 'TextStreamReader', 'TextStreamWriter', 'TextTrack',
  'TextTrackCue', 'TextTrackCueEventMap', 'TextTrackCueList',
  'TextTrackEventMap', 'TextTrackKind', 'TextTrackList',
  'TextTrackListEventMap', 'TextTrackMode', 'ThisParameterType', 'ThisType',
  'TimeLikeObject', 'TimeRanges', 'TimeUnit', 'TimeZoneLike',
  'TimelineRangeOffset', 'Timeout', 'Timer', 'TimerHandler',
  'ToStringRoundingOptions', 'ToStringRoundingOptionsWithFractionalSeconds',
  'ToggleEvent', 'ToggleEventInit', 'TogglePopoverOptions', 'Touch',
  'TouchEvent', 'TouchEventInit', 'TouchInit', 'TouchList', 'TouchType',
  'TrackEvent', 'TrackEventInit', 'TransferFunction', 'Transferable',
  'TransformStream', 'TransformStreamDefaultController', 'Transformer',
  'TransformerFlushCallback', 'TransformerStartCallback',
  'TransformerTransformCallback', 'TransitionEvent', 'TransitionEventInit',
  'TransitionOptions', 'TreeWalker', 'TypeError', 'TypeErrorConstructor',
  'TypedArray', 'TypedPropertyDescriptor', 'UIEvent', 'UIEventInit',
  'ULongRange', 'URIError', 'URIErrorConstructor', 'URL', 'URLPattern',
  'URLPatternComponentResult', 'URLPatternInit', 'URLPatternInput',
  'URLPatternOptions', 'URLPatternResult', 'URLSearchParams',
  'URLSearchParamsIterator', 'Uint16Array', 'Uint16ArrayConstructor',
  'Uint32Array', 'Uint32ArrayConstructor', 'Uint32List', 'Uint8Array',
  'Uint8ArrayConstructor', 'Uint8ClampedArray',
  'Uint8ClampedArrayConstructor', 'Uncapitalize', 'UnderlyingByteSource',
  'UnderlyingDefaultSource', 'UnderlyingSink', 'UnderlyingSinkAbortCallback',
  'UnderlyingSinkCloseCallback', 'UnderlyingSinkStartCallback',
  'UnderlyingSinkWriteCallback', 'UnderlyingSource',
  'UnderlyingSourceCancelCallback', 'UnderlyingSourcePullCallback',
  'UnderlyingSourceStartCallback', 'UnicodeBCP47LocaleIdentifier',
  'UnknownCredentialOptions', 'Uppercase', 'UserActivation',
  'UserVerificationRequirement', 'VBArray', 'VBArrayConstructor', 'VTTCue',
  'VTTRegion', 'ValidityState', 'ValidityStateFlags', 'ValueType',
  'ValueTypeMap', 'VibratePattern', 'VideoColorPrimaries', 'VideoColorSpace',
  'VideoColorSpaceInit', 'VideoConfiguration', 'VideoDecoder',
  'VideoDecoderConfig', 'VideoDecoderEventMap', 'VideoDecoderInit',
  'VideoDecoderSupport', 'VideoEncoder', 'VideoEncoderBitrateMode',
  'VideoEncoderConfig', 'VideoEncoderEncodeOptions',
  'VideoEncoderEncodeOptionsForAvc', 'VideoEncoderEventMap',
  'VideoEncoderInit', 'VideoEncoderSupport', 'VideoFacingModeEnum',
  'VideoFrame', 'VideoFrameBufferInit', 'VideoFrameCallbackMetadata',
  'VideoFrameCopyToOptions', 'VideoFrameInit', 'VideoFrameOutputCallback',
  'VideoFrameRequestCallback', 'VideoMatrixCoefficients', 'VideoPixelFormat',
  'VideoPlaybackQuality', 'VideoTransferCharacteristics', 'ViewTimeline',
  'ViewTimelineOptions', 'ViewTransition', 'ViewTransitionTypeSet',
  'ViewTransitionUpdateCallback', 'VisualViewport', 'VisualViewportEventMap',
  'VoidFunction', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_astc',
  'WEBGL_compressed_texture_etc', 'WEBGL_compressed_texture_etc1',
  'WEBGL_compressed_texture_pvrtc', 'WEBGL_compressed_texture_s3tc',
  'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info',
  'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers',
  'WEBGL_lose_context', 'WEBGL_multi_draw', 'WGSLLanguageFeatures', 'WSH',
  'WScript', 'WakeLock', 'WakeLockSentinel', 'WakeLockSentinelEventMap',
  'WakeLockType', 'WaveShaperNode', 'WaveShaperOptions', 'WeakKey',
  'WeakKeyTypes', 'WeakMap', 'WeakMapConstructor', 'WeakRef',
  'WeakRefConstructor', 'WeakSet', 'WeakSetConstructor', 'WebAssembly',
  'WebAssemblyCompileOptions', 'WebAssemblyInstantiatedSource',
  'WebCodecsErrorCallback', 'WebGL2RenderingContext',
  'WebGL2RenderingContextBase', 'WebGL2RenderingContextOverloads',
  'WebGLActiveInfo', 'WebGLBuffer', 'WebGLContextAttributes',
  'WebGLContextEvent', 'WebGLContextEventInit', 'WebGLFramebuffer',
  'WebGLPowerPreference', 'WebGLProgram', 'WebGLQuery', 'WebGLRenderbuffer',
  'WebGLRenderingContext', 'WebGLRenderingContextBase',
  'WebGLRenderingContextOverloads', 'WebGLSampler', 'WebGLShader',
  'WebGLShaderPrecisionFormat', 'WebGLSync', 'WebGLTexture',
  'WebGLTransformFeedback', 'WebGLUniformLocation', 'WebGLVertexArrayObject',
  'WebGLVertexArrayObjectOES', 'WebKitCSSMatrix', 'WebSocket',
  'WebSocketEventMap', 'WebSocketHandler', 'WebTransport',
  'WebTransportBidirectionalStream', 'WebTransportCloseInfo',
  'WebTransportCongestionControl', 'WebTransportDatagramDuplexStream',
  'WebTransportError', 'WebTransportErrorOptions', 'WebTransportErrorSource',
  'WebTransportHash', 'WebTransportOptions', 'WebTransportSendOptions',
  'WebTransportSendStreamOptions', 'WeekInfo', 'WheelEvent', 'WheelEventInit',
  'Window', 'WindowClient', 'WindowEventHandlers',
  'WindowEventHandlersEventMap', 'WindowEventMap', 'WindowLocalStorage',
  'WindowOrWorkerGlobalScope', 'WindowPostMessageOptions', 'WindowProxy',
  'WindowSessionStorage', 'WithImplicitCoercion', 'Worker', 'WorkerEventMap',
  'WorkerGlobalScope', 'WorkerGlobalScopeEventMap', 'WorkerLocation',
  'WorkerNavigator', 'WorkerOptions', 'WorkerType', 'Worklet',
  'WorkletOptions', 'WritableStream', 'WritableStreamDefaultController',
  'WritableStreamDefaultWriter', 'WriteCommandType', 'WriteParams',
  'XMLDocument', 'XMLHttpRequest', 'XMLHttpRequestBodyInit',
  'XMLHttpRequestEventMap', 'XMLHttpRequestEventTarget',
  'XMLHttpRequestEventTargetEventMap', 'XMLHttpRequestResponseType',
  'XMLHttpRequestUpload', 'XMLSerializer', 'XPathEvaluator',
  'XPathEvaluatorBase', 'XPathExpression', 'XPathNSResolver', 'XPathResult',
  'XSLTProcessor', 'YearMonthLikeObject', 'ZonedDateTime',
  'ZonedDateTimeConstructor', 'ZonedDateTimeFromOptions', 'ZonedDateTimeLike',
  'ZonedDateTimeLikeObject', 'ZonedDateTimeToStringOptions', 'global',
  'globalThis', 'process', 'structuredClone',
])
