/**
 * DtsGenerationConfig
 *
 * This is the configuration object for the DTS generation process.
 */
export interface DtsGenerationConfig {
  cwd: string
  root: string
  entrypoints: string[]
  outdir: string
  keepComments: boolean
  clean: boolean
  tsconfigPath: string
  verbose: boolean | string[]
  /**
   * Output structure: 'mirror' to mirror src folders, 'flat' for flat output
   */
  outputStructure?: 'mirror' | 'flat'
  /**
   * Import order priority patterns. Imports matching earlier patterns appear first.
   * Use 'bun', 'node:', or any string to match against the import source.
   * @default ['bun']
   * @example ['node:', 'bun', '@myorg/']
   */
  importOrder?: string[]
  /**
   * Dry run mode - show what would be generated without writing files
   */
  dryRun?: boolean
  /**
   * Show statistics after generation (files processed, declarations found, etc.)
   */
  stats?: boolean
  /**
   * Continue processing other files if one file fails
   * @default false
   */
  continueOnError?: boolean
  /**
   * Log level for controlling output verbosity
   * @default 'info'
   */
  logLevel?: 'debug' | 'info' | 'warn' | 'error' | 'silent'
  /**
   * Glob patterns to exclude from processing
   * @example ['**\/*.test.ts', '**\/__tests__/**']
   */
  exclude?: string[]
  /**
   * Output format: 'text' for human-readable, 'json' for machine-readable
   * @default 'text'
   */
  outputFormat?: 'text' | 'json'
  /**
   * Show progress during generation (file count)
   * @default false
   */
  progress?: boolean
  /**
   * Show diff of changes compared to existing .d.ts files
   * @default false
   */
  diff?: boolean
  /**
   * Validate generated .d.ts files against TypeScript compiler
   * @default false
   */
  validate?: boolean
  /**
   * Watch mode - regenerate on file changes
   * @default false
   */
  watch?: boolean
  /**
   * Process files in parallel for faster generation
   * @default false
   */
  parallel?: boolean
  /**
   * Number of concurrent workers for parallel processing
   * @default 4
   */
  concurrency?: number
  /**
   * Generate declaration map files (.d.ts.map) for source mapping
   * @default false
   */
  declarationMap?: boolean
  /**
   * Plugins for custom transformations
   * @example [stripInternalPlugin, createBannerPlugin('Generated by dtsx')]
   */
  plugins?: import('./plugins').Plugin[]
  /**
   * Bundle all declarations into a single output file
   * @default false
   */
  bundle?: boolean
  /**
   * Output filename when bundling (relative to outdir)
   * @default 'index.d.ts'
   */
  bundleOutput?: string
  /**
   * Enable incremental builds - only regenerate changed files
   * @default false
   */
  incremental?: boolean
  /**
   * Clear the incremental build cache before generating
   * @default false
   */
  clearCache?: boolean
  /**
   * Indentation style: 'spaces' or 'tabs'
   * @default 'spaces'
   */
  indentStyle?: 'spaces' | 'tabs'
  /**
   * Number of spaces for indentation (when indentStyle is 'spaces')
   * @default 2
   */
  indentSize?: number
  /**
   * Use Prettier for output formatting if available
   * @default false
   */
  prettier?: boolean
  /**
   * Glob patterns to include in processing (in addition to entrypoints)
   * More granular control over what gets processed
   * @example ['src/types/**\/*.ts', 'src/interfaces/**\/*.ts']
   */
  include?: string[]
  /**
   * Recommend isolatedDeclarations mode for best results
   * When enabled, dtsx will check that exports have explicit type annotations
   * dtsx works without it, but explicit annotations produce the most accurate .d.ts files
   * @default false
   */
  isolatedDeclarations?: boolean
  /**
   * Custom type mappings for type transformations
   * Allows replacing types during generation
   */
  typeMappings?: import('./type-mappings').TypeMappingConfig
  /**
   * Line ending style for output files
   * @default 'lf'
   */
  lineEnding?: 'lf' | 'crlf' | 'auto'
  /**
   * Normalize output formatting
   * @default true
   */
  normalizeOutput?: boolean
  /**
   * Declaration ordering configuration
   */
  declarationOrder?: {
    /** Order of declaration kinds */
    kinds?: import('./types').DeclarationKind[]
    /** Sort alphabetically within kinds */
    alphabetize?: boolean
    /** Group by export status */
    groupExports?: boolean
  }
  /**
   * Type tracking configuration for debugging
   */
  tracking?: TrackingConfig
  /**
   * Performance profiling configuration
   */
  profiling?: ProfilingConfig
  /**
   * Type inference configuration
   */
  typeInference?: TypeInferenceConfig
  /**
   * Type checking configuration
   */
  typeChecking?: TypeCheckingConfig
  /**
   * Type validation configuration
   */
  typeValidation?: TypeValidationConfig
}

/**
 * Tracking configuration for debugging type and import usage
 */
export interface TrackingConfig {
  /**
   * Track type definitions and their usage
   * @default false
   */
  types?: boolean
  /**
   * Track relationships between types (extends, implements, references)
   * @default false
   */
  relationships?: boolean
  /**
   * Track declaration usage across files
   * @default false
   */
  usage?: boolean
  /**
   * Track imports and their sources
   * @default false
   */
  imports?: boolean
  /**
   * Track which imports are actually used
   * @default false
   */
  importUsage?: boolean
  /**
   * Track import relationships (re-exports, barrel imports)
   * @default false
   */
  importRelationships?: boolean
}

/**
 * Profiling configuration for performance analysis
 */
export interface ProfilingConfig {
  /**
   * Enable memory profiling
   * @default false
   */
  memory?: boolean
  /**
   * Memory limit in MB (warning when exceeded)
   * @default 1024
   */
  memoryLimit?: number
  /**
   * Enable CPU profiling
   * @default false
   */
  cpu?: boolean
  /**
   * CPU sampling interval in milliseconds
   * @default 100
   */
  samplingInterval?: number
  /**
   * Enable I/O profiling
   * @default false
   */
  io?: boolean
  /**
   * I/O operations to track
   * @default ['read', 'write']
   */
  trackOperations?: ('read' | 'write')[]
  /**
   * Output profiling results to file
   */
  outputFile?: string
}

/**
 * Type inference configuration
 */
export interface TypeInferenceConfig {
  /**
   * Enable type inference
   * @default true
   */
  enabled?: boolean
  /**
   * Inference strictness level
   * - 'loose': Infer any when uncertain
   * - 'normal': Balance between inference and explicit types
   * - 'strict': Require explicit types for ambiguous cases
   * @default 'normal'
   */
  strictness?: 'loose' | 'normal' | 'strict'
  /**
   * Infer return types for functions without explicit annotations
   * @default true
   */
  inferReturnTypes?: boolean
  /**
   * Infer const assertion types
   * @default true
   */
  inferConstTypes?: boolean
}

/**
 * Type checking configuration
 */
export interface TypeCheckingConfig {
  /**
   * Enable type checking during generation
   * @default false
   */
  enabled?: boolean
  /**
   * Type checking strictness level
   * @default 'normal'
   */
  strictness?: 'loose' | 'normal' | 'strict'
  /**
   * Treat warnings as errors
   * @default false
   */
  warningsAsErrors?: boolean
  /**
   * Maximum number of type errors before stopping
   * @default 100
   */
  maxErrors?: number
}

/**
 * Type validation configuration
 */
export interface TypeValidationConfig {
  /**
   * Enable type validation
   * @default false
   */
  enabled?: boolean
  /**
   * Validation rules
   */
  rules?: {
    /**
     * Disallow 'any' type
     * @default false
     */
    noAny?: boolean
    /**
     * Disallow 'unknown' type
     * @default false
     */
    noUnknown?: boolean
    /**
     * Disallow implicit any
     * @default false
     */
    noImplicitAny?: boolean
    /**
     * Require explicit return types
     * @default false
     */
    explicitReturnTypes?: boolean
    /**
     * Require explicit function parameter types
     * @default false
     */
    explicitParameterTypes?: boolean
  }
}

/**
 * Source location for error reporting
 */
export interface SourceLocation {
  line: number
  column: number
  offset?: number
}

/**
 * Detailed error information with source location
 */
export interface DtsError {
  file: string
  message: string
  code?: string
  location?: SourceLocation
  stack?: string
  suggestion?: string
}

/**
 * Generation statistics
 */
export interface GenerationStats {
  filesProcessed: number
  filesGenerated: number
  filesFailed: number
  filesValidated: number
  validationErrors: number
  declarationsFound: number
  importsProcessed: number
  exportsProcessed: number
  durationMs: number
  errors: DtsError[]
}

/**
 * DtsGenerationOption
 *
 * This is the configuration object for the DTS generation process.
 */
export type DtsGenerationOption = Partial<DtsGenerationConfig>

/**
 * DtsGenerationOptions
 *
 * This is the configuration object for the DTS generation process.
 */
export type DtsGenerationOptions = DtsGenerationOption | DtsGenerationOption[]

/**
 * Declaration kind - all possible declaration types
 */
export type DeclarationKind = 'function' | 'variable' | 'interface' | 'type' | 'class' | 'enum' | 'import' | 'export' | 'module' | 'namespace' | 'unknown'

/**
 * Declaration
 *
 * Represents a parsed declaration from TypeScript source
 */
export interface Declaration {
  kind: DeclarationKind
  name: string
  text: string
  leadingComments?: string[]
  isExported: boolean
  isDefault?: boolean
  typeAnnotation?: string
  modifiers?: string[]
  generics?: string
  extends?: string
  implements?: string[]
  members?: Declaration[]
  parameters?: ParameterDeclaration[]
  returnType?: string
  value?: unknown
  source?: string // for imports
  specifiers?: ImportSpecifier[] // for imports
  isTypeOnly?: boolean // for imports/exports
  isSideEffect?: boolean // for side-effect imports like `import 'module'`
  isAsync?: boolean
  isGenerator?: boolean
  overloads?: string[] // for function overloads
  start?: number // AST node start position
  end?: number // AST node end position
}

/**
 * ParameterDeclaration
 */
export interface ParameterDeclaration {
  name: string
  type?: string
  optional?: boolean
  rest?: boolean
  defaultValue?: string
}

/**
 * ImportSpecifier
 */
export interface ImportSpecifier {
  name: string
  alias?: string
  isType?: boolean
}

/**
 * ProcessingContext
 *
 * Context passed through processing pipeline
 */
export interface ProcessingContext {
  filePath: string
  sourceCode: string
  declarations: Declaration[]
  imports: Map<string, Set<string>>
  exports: Set<string>
  usedTypes: Set<string>
}
